### ISSUE TITLE
didn't support dependence swagger-ui-lite@2015.11.1

### ISSUE THREAD

**Issue by DexterYan** [kaizhu256/node-swagger-mongodb#1]
after npm install, the testing didn't work. I check it if change back to swagger-ui-lite@2015.6.1, it is ok. Can you check it?

**Comment by kaizhu256** [comment]
gonna publish v2015.8.3 and lock npm dependencies to last successful build @ https://travis-ci.org/kaizhu256/node-swagger-mongodb/jobs/76399404#L162

**Comment by kaizhu256** [comment]
hmm, it still freezes on travis-ci.  need to look into it more

**Comment by DexterYan** [comment]
you can git clone it into your machine, and do npm install, you will find swagger-ui-lite is now been upgraded to 2015.11.1

**Comment by kaizhu256** [comment]
published v2015.8.3 with locked down dependency version.  passed all tests @ https://travis-ci.org/kaizhu256/node-swagger-mongodb/

**Comment by kaizhu256** [comment]
fyi, i found the cause of the issue @ https://github.com/swagger-api/swagger-ui/issues/1778
